<a href="https://colab.research.google.com/github/katerynal-commits/-4-for/blob/main/HW7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [15]:
import numpy as np  # імпорт бібліотеки NumPy
arr = np.array([5, 15, 25, 35, 45])
print(arr) #масив зі списку
zeros_arr = np.zeros(7, dtype=int)
print(zeros_arr) #масив з нулів розміром 7
ones_arr = np.ones(6, dtype=int)
print(ones_arr) #масив одиниць розміром 6
range_arr = np.arange(10, 20)
print(range_arr)  #масив від 10 до 19

[ 5 15 25 35 45]
[0 0 0 0 0 0 0]
[1 1 1 1 1 1]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [16]:
import numpy as np  # імпорт бібліотеки NumPy
arr = np.array([12, 24, 36, 48, 60])
multiplied = arr * 2
print(multiplied) #Х2
added = arr + 10
print(added)  # +10
squared = arr ** 2
print(squared) # цифри у квадраті
sqrt_arr = np.sqrt(arr)
print(sqrt_arr) # квадратний корінь з усіх елементів

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [17]:
import numpy as np  # імпорт бібліотеки NumPy
arr = np.array([18, 27, 33, 41, 52, 68, 79])
print(arr)
mean_value = np.mean(arr)
print(mean_value)  #середнє значення
min_value = np.min(arr)
print(min_value) #мінімум
max_value = np.max(arr)
print(max_value) #максимум
sum_value = np.sum(arr)
print(sum_value)  #сума


[18 27 33 41 52 68 79]
45.42857142857143
18
79
318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [18]:
import numpy as np  # імпорт бібліотеки NumPy
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr[0]) #перший елемент
print(arr[-1]) #останній елемент
print(arr[1:4]) #елементи з індексами 1 до 3
arr[arr > 40]

15
67
[22 35 44]


array([44, 58, 67])


---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [19]:
import numpy as np  # імпорт бібліотеки NumPy

matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
print(matrix.shape)


(3, 3)


In [20]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
print(matrix[0]) #перший рядок

[2 4 6]


In [21]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
print(matrix[:,1]) #друга колонка

[ 4 10 16]


In [22]:
import numpy as np  # імпорт бібліотеки NumPy
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
print(np.sum (matrix)) #сума

90


In [23]:
import numpy as np  # імпорт бібліотеки NumPy
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])
print(np.mean (matrix)) #сума

10.0
